version: "3.9"
services:
  tick:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - ./database/:/app/database:rw
    command: node tick.js
  eddn:
    build: .
    volumes:
      - ./database/:/app/database:rw
    command: node EDDN.js
  detector:
    build: .
    volumes:
      - ./database/:/app/database:rw
    command: node detector.js
